# Generated by Django 5.2.14 on 2026-08-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('SSLCOMMERZ', 'SSLCommerz')], default='COD', max_length=20),
        ),
    ]
